# Generated by Django 5.1 on 2024-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('student_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('answers', models.TextField()),
                ('correct_answers', models.TextField()),
                ('question_number', models.IntegerField()),
                ('subject_contents', models.TextField()),
                ('assessment_areas', models.TextField()),
                ('sydney_correct_count_percentage', models.FloatField()),
                ('sydney_average_score', models.FloatField()),
                ('sydney_participants', models.IntegerField()),
                ('student_score', models.FloatField()),
                ('student_total_assessed', models.IntegerField()),
                ('student_area_assessed_score', models.FloatField()),
                ('total_area_assessed_score', models.FloatField()),
                ('participant', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.FloatField()),
                ('average_score', models.FloatField()),
                ('school_percentile', models.FloatField()),
                ('sydney_percentile', models.FloatField()),
                ('strength_status', models.CharField(max_length=50)),
                ('high_distinct_count', models.IntegerField()),
                ('distinct_count', models.IntegerField()),
                ('credit_count', models.IntegerField()),
                ('participant_count', models.IntegerField()),
                ('award', models.CharField(max_length=100)),
            ],
        ),
    ]
