# Generated by Django 5.1 on 2024-08-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
