# Generated by Django 5.1 on 2024-08-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentdata_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='credit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='distinct_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='high_distinct_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='participant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='participant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_total_assessed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='sydney_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
