# Generated by Django 5.1 on 2024-08-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentdata_credit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
