# Generated by Django 5.1 on 2024-08-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentdata_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
