# Generated by Django 5.1 on 2024-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentdata_first_name_alter_studentdata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
