# Generated by Django 5.1 on 2024-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_studentdata_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
