# Generated by Django 5.1 on 2024-08-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_studentdata_student_id_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_area1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentdata')),
            ],
        ),
    ]
